### ISSUE TITLE
JCE cannot authenticate the provider AndroidKeyStore

### ISSUE THREAD

**Issue by jeorgearomal** [appmattus/layercache#39]
When we included the test class EncryptedSharedPreferencesCacheIntegrationShould.kt we get the below exception.
If you have faced similar issue then, kindly share the steps

java.security.NoSuchProviderException: JCE cannot authenticate the provider AndroidKeyStore

	at javax.crypto.JceSecurity.getInstance(JceSecurity.java:105)
	at javax.crypto.KeyGenerator.getInstance(KeyGenerator.java:265)
	at androidx.security.crypto.MasterKeys.generateKey(MasterKeys.java:138)
	at androidx.security.crypto.MasterKeys.getOrCreate(MasterKeys.java:97)
	at androidx.security.crypto.MasterKey$Builder.buildOnM(MasterKey.java:357)
	at androidx.security.crypto.MasterKey$Builder.build(MasterKey.java:314)
	at com.appmattus.layercache.EncryptedSharedPreferencesCacheIntegrationShould.<init>(EncryptedSharedPreferencesCacheIntegrationShould.kt:42)
	at org.junit.runners.BlockJUnit4ClassRunner.createTest(BlockJUnit4ClassRunner.java:250)
	at org.robolectric.RobolectricTestRunner$HelperTestRunner.createTest(RobolectricTestRunner.java:561)
	at org.junit.runners.BlockJUnit4ClassRunner.createTest(BlockJUnit4ClassRunner.java:260)
	at org.junit.runners.BlockJUnit4ClassRunner$2.runReflectiveCall(BlockJUnit4ClassRunner.java:309)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.BlockJUnit4ClassRunner.methodBlock(BlockJUnit4ClassRunner.java:306)
	at org.robolectric.internal.SandboxTestRunner$HelperTestRunner.methodBlock(SandboxTestRunner.java:344)
	at org.robolectric.RobolectricTestRunner$HelperTestRunner.methodBlock(RobolectricTestRunner.java:570)
	at org.robolectric.internal.SandboxTestRunner$2.lambda$evaluate$0(SandboxTestRunner.java:274)
	at org.robolectric.internal.bytecode.Sandbox.lambda$runOnMainThread$0(Sandbox.java:89)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.util.jar.JarException: Class is on the bootclasspath
	at javax.crypto.JarVerifier.verify(JarVerifier.java:286)
	at javax.crypto.JceSecurity.verifyProviderJar(JceSecurity.java:164)
	at javax.crypto.JceSecurity.getVerificationResult(JceSecurity.java:190)
	at javax.crypto.JceSecurity.getInstance(JceSecurity.java:102)
	at javax.crypto.KeyGenerator.getInstance(KeyGenerator.java:265)
	at androidx.security.crypto.MasterKeys.$$robo$$androidx_security_crypto_MasterKeys$generateKey(MasterKeys.java:138)
	at androidx.security.crypto.MasterKeys.generateKey(MasterKeys.java)
	at androidx.security.crypto.MasterKeys.$$robo$$androidx_security_crypto_MasterKeys$getOrCreate(MasterKeys.java:97)
	at androidx.security.crypto.MasterKeys.getOrCreate(MasterKeys.java)
	at androidx.security.crypto.MasterKey$Builder.$$robo$$androidx_security_crypto_MasterKey_Builder$buildOnM(MasterKey.java:357)
	at androidx.security.crypto.MasterKey$Builder.buildOnM(MasterKey.java)
	at androidx.security.crypto.MasterKey$Builder.$$robo$$androidx_security_crypto_MasterKey_Builder$build(MasterKey.java:314)
	at androidx.security.crypto.MasterKey$Builder.build(MasterKey.java)
	at com.appmattus.layercache.EncryptedSharedPreferencesCacheIntegrationShould.<init>(EncryptedSharedPreferencesCacheIntegrationShould.kt:42)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)

**Comment by crjacinro** [comment]
I used the same logic in Android Keystore Provider and Robolectric Store for unit tests and I see the same error as you have.

**Comment by mattmook** [comment]
I have figured out a solution to the above exception now and will be adding it to the project over the next few days.

As stated above the issue is because of JceSecurity requiring the provider to be signed.

While not usually advised, fortunately it looks like we can mock the static function that causes the problem as follows:

```kotlin
    private lateinit var jce: MockedStatic<out Any>

    @Before
    fun setup() {
        // Disable 
        jce = mockStatic(Class.forName("javax.crypto.JceSecurity")) {
            if (it.method.name == "getVerificationResult") null else it.callRealMethod()
        }
    }

    @After
    fun tearDown() {
        jce.close()
    }
```
